package net.viperfish.latinQuiz.core;

public enum Tense {
	PRESENT, IMPERFECT, FUTURE, PERFECT, FUTURE_PERFECT, PLUPERFECT, PRESENT_PASSIVE, IMPERFECT_PASSIVE, FUTURE_PASSIVE, PERFECT_PASSIVE, PLUPERFECT_PASSIVE, FUTURE_PERFECT_PASSIVE;
}
